# Generated by Django 6.0.6 on 2026-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_job_title_user_phone_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
