# Generated by Django 6.0.6 on 2026-07-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar',
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
