# Generated by Django 6.0.6 on 2026-06-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_department_alter_course_academic_year'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=100)),
                ('grade_letter', models.CharField(blank=True, max_length=5)),
                ('assessment_type', models.CharField(help_text='e.g. Quiz, Lab, Essay, Exam', max_length=100)),
                ('assessment_name', models.CharField(help_text='e.g. Calculus Quiz, Biology Lab', max_length=200)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
