# Generated by Django 6.0.6 on 2026-06-29 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_insight', models.TextField(help_text="Teacher's observation about the student")),
                ('performance_strengths', models.JSONField(default=list, help_text='List of strengths e.g. ["Analytical Reasoning", "Participation"]')),
                ('class_rank', models.CharField(blank=True, help_text='e.g. Top 5% of 10th Grade', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='students.student')),
            ],
        ),
    ]
