# Generated by Django 6.0.6 on 2026-06-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinsight',
            name='emergency_contacts',
            field=models.JSONField(default=list, help_text='[{"name": "Sarah", "relation": "Mother (Primary)", "phone": "1234567890", "is_primary": true}]'),
        ),
        migrations.AddField(
            model_name='studentinsight',
            name='extracurriculars',
            field=models.JSONField(default=list, help_text='["Honors Program", "Varsity Soccer"]'),
        ),
        migrations.AddField(
            model_name='studentinsight',
            name='medical_alerts',
            field=models.JSONField(default=list, help_text='[{"title": "Nut Allergy", "detail": "Carries EpiPen"}]'),
        ),
        migrations.AlterField(
            model_name='studentinsight',
            name='academic_insight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentinsight',
            name='class_rank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinsight',
            name='performance_strengths',
            field=models.JSONField(default=list),
        ),
    ]
