# Generated by Django 6.0.6 on 2026-07-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_course_schedule_grade_schedule_subject_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertimetable',
            name='source_schedule',
            field=models.OneToOneField(blank=True, help_text='Auto-managed link back to the Schedule entry that generated this row.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entry', to='schedules.schedule'),
        ),
    ]
