# Generated by Django 6.0.6 on 2026-06-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('holiday', 'Holiday'), ('upcoming', 'Upcoming')], default='present', max_length=20)),
                ('event_name', models.CharField(help_text='e.g. Science Fair, Regular School Day', max_length=200)),
                ('event_type', models.CharField(blank=True, help_text='e.g. Academic Deadline, Standard Attendance', max_length=100)),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
